name: AutoPR
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  autopr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate PR Title & Description
        uses: irgolic/autopr@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
